name: Run Sedstart Testcases

on:
  workflow_dispatch:

jobs:
  run-sedstart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call Sedstart API
        run: |
          curl -X POST "https://app.sedstart.com/api/run" \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.SEDSTART_API_KEY }}" \
          -d '{"project": "sample", "environment": "prod"}'

